POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlzYWFjQGV4YW1wbGUuY29tIiwiZXhwIjoxNzEyNTAxNjcxLCJ1c2VySWQiOjF9.lAKPfMwANFMb4O4PNRcsNMPtV_IC5HKIeirSPBuFZYA

{
    "name": "Isaac's Event",
    "description": "Learning Go",
    "location": "Mental Prison",
    "dateTime": "2025-01-01T15:30:00.000Z"
}